version: '2.1'

services:
  terrycentos:
    image: furywolf/centosprod
    container_name: centosprod
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - d:/docker/volumes/centos:/mnt/shared:rw
    ports:
      - "21:21"
      - "2122:22"
      - "64000-64010:64000-64010"