version: '2.1'

services:
  wildfly:
    image: furywolf/centoslocal_wildfly
    container_name: centoslocal_wildfly
    volumes:
      - d:/docker/volumes/wildfly/standalone/deployments:/opt/jboss/wildfly/standalone/deployments:rw
    ports:
      - "8787:8787"
      - "8080:8080"
      - "9990:9990"