# network는 dockernet 이라는 별도의 network를 만들어서 여기에서 실행이 되도록 했다
# 아래와 같이 dockernet 이라는 network를 먼저 만들고 난 뒤에 docker-compose를 실행하도록 한다
# docker network create -d bridge --subnet 192.168.100.0/24 --gateway 192.168.100.1 dockernet
version: '2.1'

services:
  terrycentos:
    image: furywolf/centoslocal
    container_name: centoslocal
#    volumes:
#      - d:/docker/volumes/centos:/mnt/shared:rw
    ports:
      - "8080:8080"
    networks:
      dockernet:
        ipv4_address: 192.168.100.11
    stdin_open: true
    tty: true
networks:
  dockernet:
    external: true