# network는 dockernet 이라는 별도의 network를 만들어서 여기에서 실행이 되도록 했다
# 아래와 같이 dockernet 이라는 network를 먼저 만들고 난 뒤에 docker-compose를 실행하도록 한다
# docker network create -d bridge --subnet 192.168.100.0/24 --gateway 192.168.100.1 dockernet
version: '2.1'

services:
  centosprod_redmine:
    image: furywolf/centosprod_redmine
    container_name: redmine
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - d:/docker/volumes/centosprod:/mnt/shared:rw
    ports:
      - "21:21"
      - "2122:22"
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "8080:8080"
      - "64000-64010:64000-64010"
    networks:
      dockernet:
        ipv4_address: 192.168.100.21
networks:
  dockernet:
    external: true