# network는 dockernet 이라는 별도의 network를 만들어서 여기에서 실행이 되도록 했다
# 아래와 같이 dockernet 이라는 network를 먼저 만들고 난 뒤에 docker-compose를 실행하도록 한다
# docker network create -d bridge --subnet 192.168.100.0/24 --gateway 192.168.100.1 dockernet
version: '2.1'

services:
  oracledb:
    image: furywolf/centoslocal_oracle-xe
    container_name: centoslocal_oracle-xe
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - d:/docker/volumes/oracle/tablespaces:/mnt/shared/tablespaces:rw
    ports:
      - "21:21"
      - "2122:22"
      - "1521:1521"
      - "18080:8080"
      - "64000-64010:64000-64010"
    networks:
      dockernet:
        ipv4_address: 192.168.100.13
networks:
  dockernet:
    external: true